# workflow name
name: release

# on events
on:
  release:
    types:
      - created

# jobs
jobs:
  build:
    name: Build cross-platform & Add to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build for Linux
        env:
          CGO_ENABLED: 1
          GOARCH: amd64
          GOOS: linux
        run: >
          go build -buildmode=plugin -o build/linux-amd64/plugins/cloudflare.so ./cmd/plugins/cloudflare/cloudflare.go &&
          go build -o build/linux-amd64/DynGoDNS ./cmd/DynGoDNS/main.go

      - name: Archive builds
        run: >
          cd build/linux-amd64 && tar -czf ../linux-amd64.tar.gz . && cd ../..

      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./build/*.tar.gz"
